DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS books;

CREATE TABLE genres (
  ID INT NOT NULL,
  GENRE_NAME VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE authors (
  ID INT NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE books (
  ID INT NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  AUTHOR_ID INT NOT NULL,
  GENRE_ID INT NOT NULL,
  PRIMARY KEY (ID),
  foreign key (AUTHOR_ID) references authors(ID),
  foreign key (GENRE_ID) references genres(ID)
);